# Generated by Django 5.2.15 on 2026-06-26 04:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('citizen', 'Mwananchi'), ('village_leader', 'Kiongozi wa Kijiji'), ('water_officer', 'Wafanyakazi wa Maji'), ('district_officer', 'Mfanyikazi wa Wilaya'), ('admin', 'Msimamizi')], default='citizen', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watertrack_app.village')),
            ],
            options={
                'db_table': 'watertrack_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('shallow_well', 'Kisima cha Juu'), ('deep_well', 'Kisima cha Kina'), ('spring', 'Chemchem'), ('river', 'Mto'), ('dam', 'Bwawa'), ('borehole', 'Bomba la Kuchimba'), ('rainwater', 'Maji ya Mvua')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('safe', 'Salama'), ('caution', 'Tahadhari'), ('unsafe', 'Hatarini'), ('under_repair', 'Inatengenezwa'), ('dry', 'Kavu')], default='safe', max_length=20)),
                ('ph_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('bacteria_count', models.PositiveIntegerField(blank=True, null=True)),
                ('iron_level', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('turbidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('last_cleaned', models.DateField(blank=True, null=True)),
                ('next_cleaning', models.DateField(blank=True, null=True)),
                ('construction_year', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='water_sources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_sources', to='watertrack_app.village')),
            ],
        ),
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bacteria_count', models.PositiveIntegerField()),
                ('iron_level', models.DecimalField(decimal_places=3, max_digits=6)),
                ('turbidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chlorine_level', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('is_safe', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('water_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reports', to='watertrack_app.watersource')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Ndogo'), ('medium', 'Wastani'), ('high', 'Kubwa'), ('critical', 'Dharura')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('assigned', 'Imepewa Wafanyakazi'), ('in_progress', 'Inafanywa Kazi'), ('resolved', 'Imetatuliwa'), ('closed', 'Imefungwa')], default='pending', max_length=15)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('water_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='watertrack_app.watersource')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('quality_drop', 'Ubora Umeshuka'), ('source_dry', 'Chanzo Kimekauka'), ('damage', 'Uharibifu'), ('maintenance_due', 'Usafishaji Umekaribia'), ('general', 'Ujumbe Mkuu')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.ManyToManyField(related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('water_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watertrack_app.watersource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
