# Generated by Django 5.2.10 on 2026-07-04 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watertrack_app', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
