# Generated by Django 5.2.15 on 2026-07-07 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watertrack_app', '0003_alter_damagereport_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='forwarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='village_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='village_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='village_approved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='status',
            field=models.CharField(choices=[('pending_village', 'Inasubiri Idhini ya Mwenyekiti'), ('village_approved', 'Imeidhinishwa na Mwenyekiti'), ('forwarded_to_district', 'Imetumwa kwa Wilaya'), ('rejected', 'Imekataliwa'), ('assigned', 'Imepewa Wafanyakazi'), ('in_progress', 'Inafanywa Kazi'), ('resolved', 'Imetatuliwa'), ('closed', 'Imefungwa'), ('pending', 'Inasubiri (Zamani)')], default='pending_village', max_length=30),
        ),
    ]
